--shellExecute([["C:\DATA\Games\bblit2.exe"]]); --open the game
getAutoAttachList().add('bblit2.exe')  --ce will now watch the process

function onOpenProcess(pid)
  local t=createTimer()
  t.OnInterval=7000 --wait 7 seconds to let the game load (change this accordingly. If it's a cheat that needs to be activated after loading a game, set it to a minute or two)

  t.OnTimer=function(x)
    local al=getAddressList()
    al.getMemoryRecordByDescription('Horizontal').Active=true
    al.getMemoryRecordByDescription('Horizontal').Value=38
    al.getMemoryRecordByDescription('Vertical').Active=true
    al.getMemoryRecordByDescription('Vertical').Value=38
    x.destroy() --the timer is not needed anymore
  end
end

local t=createTimer(MainForm)
t.Interval=1000
t.OnTimer=function()
  if getOpenedProcessID()~=0 and readInteger(process)==nil then
    t.destroy()
    closeCE()
  end
end --check every second if the game is running, if not, close CE

--CETrainer.hide()
--TRAINERGENERATORSTART--
--This is autogenerated code. Changing code in this block will
--get erased and rewritten if you regenerate the trainer code

--Uncomment the following line if this is a Cheat Table format trainer and you don't want CE to show (Tip, save as .CETRAINER alternatively)
--hideAllCEWindows()

--RequiredCEVersion=7.3
--if (getCEVersion==nil) or (getCEVersion()<RequiredCEVersion) then
  --messageDialog('Please install Cheat Engine '..RequiredCEVersion, mtError, mbOK)
  --closeCE()
--end

getAutoAttachList().add("bblit2.exe")
gPlaySoundOnAction=false
--CETrainer.fixDPI() --remove this if you have already taken care of DPI issues yourself
--CETrainer.show()
function AboutClick()
  showMessage(gAboutText)
end
gAboutText=[[]]

function CloseClick()
  --called by the close button onClick event, and when closing the form
  closeCE()
  return caFree --onClick doesn't care, but onClose would like a result
end

--TRAINERGENERATORSTOP--
